name: absenku_u_a_s
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  animated: ^2.0.0
  animated_card: ^2.0.0
  animated_size_and_fade: ^3.0.0
  animated_stack: ^0.2.0
  cool_alert: ^1.1.0
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.9.1
  flutter:
    sdk: flutter
  flutter_calendar_carousel: ^2.4.1
  flutter_svg: ^1.1.6
  flutter_swipe_detector: ^2.0.0
  get: 4.6.5
  get_storage: ^2.0.3
  getwidget: ^3.0.1
  google_nav_bar: ^5.0.6
  http: ^0.13.5
  rflutter_alert: ^2.0.4
  simple_gesture_detector: ^0.2.0
  swipedetector: ^1.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/icon/
    - assets/image/
    - assets/image/LogoAbsenku.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Medium.ttf
